#!/bin/bash

docker build \
    -t jakerbeck/pukel-docker-airflow-with-epoch8-exporter:${VERSION} \
    --build-arg VERSION="${VERSION}" \
    .

docker push jakerbeck/pukel-docker-airflow-with-epoch8-exporter:${VERSION}
docker push jakerbeck/pukel-docker-airflow-with-epoch8-exporter:latest
